import fs from "fs/promises";
import path from "path";
import { getClaudeHome, isSubPath } from "../utils/pathUtils.js";
import { logger } from "../utils/logger.js";
import type {
  SessionInfo,
  FileBackupMeta,
  CheckpointData,
  CheckpointsResult,
  FileRollbackResult,
  RollbackResult,
} from "../types/api.js";

/**
 * Encode a filesystem path to the hash Claude Code uses for project directories.
 * Claude Code replaces every non-alphanumeric character with '-'.
 * e.g. "E:\work\my project" → "E--work-my-project"
 */
function pathToHash(p: string): string {
  return p.replace(/\\/g, "/").replace(/[^a-zA-Z0-9]/g, "-");
}

/**
 * Check if a user message is a CLI-internal message that should not be shown.
 * Filters out:
 *   - "[...]" — system tags like [Request interrupted by user]
 *   - "<...>" — XML-tagged local commands (local-command-caveat, command-name, etc.)
 *   - Compact continuation summaries ("This session is being continued...")
 */
function isInternalMessage(text: string): boolean {
  return text.startsWith("[")
    || text.startsWith("<")
    || text.startsWith("This session is being continued");
}

/**
 * Known prefixes for auto-generated session starters (e.g., plan mode execution).
 * These sessions are created by Claude Code CLI, not by the user directly.
 */
const AUTO_SESSION_PREFIXES = [
  "Implement the following plan",
  "Reply with exactly",
  "If you need specific details from before exiting plan mode",
] as const;

/**
 * Check if a first user message indicates this session was auto-generated
 * by Claude Code (plan mode, skill invocation, etc.).
 */
function isAutoGeneratedStart(text: string): boolean {
  return AUTO_SESSION_PREFIXES.some((prefix) => text.startsWith(prefix));
}

/**
 * Extract a human-friendly title from an auto-generated session's first message.
 * For plan sessions: extracts the first Markdown heading (# Title).
 * Falls back to a generic label if no heading is found.
 */
function extractPlanTitle(text: string): string {
  // Look for first markdown heading: "# Title"
  const match = text.match(/^#+\s+(.+)$/m);
  if (match) {
    const title = match[1].trim();
    return title.slice(0, 60) + (title.length > 60 ? "…" : "");
  }
  // Fallback: take first 40 chars after the prefix
  for (const prefix of AUTO_SESSION_PREFIXES) {
    if (text.startsWith(prefix)) {
      const rest = text.slice(prefix.length).replace(/^[:\s]+/, "").trim();
      if (rest) return rest.slice(0, 50) + (rest.length > 50 ? "…" : "");
    }
  }
  return "Plan 执行";
}

/**
 * Extract text from a user message content field (string or array of blocks).
 */
function extractUserText(content: unknown): string {
  if (typeof content === "string") return content;
  if (Array.isArray(content)) {
    return (content as { type: string; text?: string }[])
      .filter((b) => b.type === "text" && b.text)
      .map((b) => b.text!)
      .join("");
  }
  return "";
}

/**
 * Read the first ~32 KB of a JSONL session file to extract session metadata:
 * - name: first real user message text (truncated to 60 chars)
 * - projectPath: the `cwd` field from the first user entry
 * - isPlanExecution: true if this session was auto-created by plan mode
 */
async function readSessionMeta(filePath: string): Promise<{
  name: string | null;
  projectPath: string | null;
  isPlanExecution: boolean;
}> {
  try {
    const fd = await fs.open(filePath, "r");
    // For plan sessions, the plan content can be large — read more to find the # heading
    const buffer = Buffer.alloc(65536);
    const { bytesRead } = await fd.read(buffer, 0, 65536, 0);
    await fd.close();

    const content = buffer.subarray(0, bytesRead).toString("utf-8");
    const lines = content.split("\n");

    let name: string | null = null;
    let projectPath: string | null = null;
    let isPlanExecution = false;

    for (const line of lines) {
      if (!line.trim()) continue;
      try {
        const parsed = JSON.parse(line) as {
          type?: string;
          cwd?: string;
          message?: { role?: string; content?: unknown };
        };
        if (parsed.type !== "user" || !parsed.message) continue;

        // Extract cwd from the first user entry (always present on the first one)
        if (!projectPath && parsed.cwd) {
          projectPath = parsed.cwd;
        }

        // Extract session name from the first real user message
        if (!name) {
          const trimmed = extractUserText(parsed.message.content).trim();
          if (trimmed && !isInternalMessage(trimmed)) {
            if (isAutoGeneratedStart(trimmed)) {
              isPlanExecution = true;
              name = extractPlanTitle(trimmed);
            } else {
              name = trimmed.slice(0, 60) + (trimmed.length > 60 ? "…" : "");
            }
          }
        }

        // Stop early once we have both
        if (name && projectPath) break;
      } catch {
        /* malformed JSON line — skip */
      }
    }
    return { name, projectPath, isPlanExecution };
  } catch {
    return { name: null, projectPath: null, isPlanExecution: false };
  }
}

/**
 * Entry from Claude Code's sessions-index.json.
 * This file contains rich metadata per session maintained by the CLI.
 */
interface SessionsIndexEntry {
  sessionId: string;
  summary?: string;
  model?: string;
  gitBranch?: string;
  messageCount?: number;
  parentSessionId?: string | null;
  lastActiveAt?: string;
  createdAt?: string;
}

export class SessionManager {
  /**
   * Read sessions-index.json from a project directory.
   * Returns a map of sessionId → SessionsIndexEntry.
   */
  private async readSessionsIndex(projectDir: string): Promise<Map<string, SessionsIndexEntry>> {
    const indexPath = path.join(projectDir, "sessions-index.json");
    const map = new Map<string, SessionsIndexEntry>();
    try {
      const raw = await fs.readFile(indexPath, "utf-8");
      const parsed = JSON.parse(raw) as { sessions?: Record<string, SessionsIndexEntry> };
      if (parsed.sessions) {
        for (const [id, entry] of Object.entries(parsed.sessions)) {
          map.set(id, { ...entry, sessionId: entry.sessionId || id });
        }
      }
    } catch {
      // sessions-index.json may not exist or be malformed — that's fine
    }
    return map;
  }

  /**
   * Find the JSONL file path for a given session ID by scanning all project directories.
   */
  private async findSessionJsonl(sessionId: string): Promise<string | null> {
    const projectsDir = path.join(getClaudeHome(), "projects");
    try {
      const dirs = await fs.readdir(projectsDir);
      for (const dir of dirs) {
        const candidate = path.join(projectsDir, dir, `${sessionId}.jsonl`);
        const exists = await fs.access(candidate).then(() => true).catch(() => false);
        if (exists) return candidate;
      }
    } catch { /* projects dir doesn't exist */ }
    return null;
  }

  /**
   * List sessions from ~/.claude/projects/.
   * If projectPath is provided, only returns sessions for that specific project.
   * Otherwise returns sessions across all projects, sorted newest first.
   *
   * Enriches results with data from sessions-index.json when available
   * (summary, model, gitBranch, messageCount, parentSessionId).
   */
  async listSessions(projectPath?: string): Promise<SessionInfo[]> {
    const projectsDir = path.join(getClaudeHome(), "projects");
    const sessions: SessionInfo[] = [];

    // Determine which project directories to scan
    let dirsToScan: string[];
    if (projectPath) {
      dirsToScan = [pathToHash(projectPath)];
    } else {
      try {
        dirsToScan = await fs.readdir(projectsDir);
      } catch {
        return [];
      }
    }

    for (const dir of dirsToScan) {
      const fullDir = path.join(projectsDir, dir);
      const stat = await fs.stat(fullDir).catch(() => null);
      if (!stat?.isDirectory()) continue;

      // Read sessions-index.json for this project directory
      const indexMap = await this.readSessionsIndex(fullDir);

      const files = await fs.readdir(fullDir).catch(() => []);
      for (const f of files) {
        if (!f.endsWith(".jsonl")) continue;
        const filePath = path.join(fullDir, f);
        const fstat = await fs.stat(filePath).catch(() => null);
        if (!fstat) continue;

        const sessionId = f.replace(".jsonl", "");
        const indexEntry = indexMap.get(sessionId);

        // Parse first user message for session title and project path
        const meta = await readSessionMeta(filePath);

        // Check if the original project folder still exists on disk
        let projectPathValid = false;
        if (meta.projectPath) {
          projectPathValid = await fs.access(meta.projectPath).then(() => true).catch(() => false);
        }

        // Prefer sessions-index.json data over JSONL fallbacks
        sessions.push({
          id: sessionId,
          name: meta.name,
          model: indexEntry?.model || null,
          projectPath: meta.projectPath,
          projectPathValid,
          messageCount: indexEntry?.messageCount ?? 0,
          createdAt: indexEntry?.createdAt || fstat.birthtime.toISOString(),
          updatedAt: indexEntry?.lastActiveAt || fstat.mtime.toISOString(),
          isActive: false,
          summary: indexEntry?.summary || null,
          gitBranch: indexEntry?.gitBranch || null,
          parentSessionId: indexEntry?.parentSessionId ?? null,
          isPlanExecution: meta.isPlanExecution,
        });
      }
    }

    logger.info(`Sessions loaded: ${sessions.length} (project=${projectPath || "all"})`);
    return sessions.sort(
      (a, b) =>
        new Date(b.updatedAt).getTime() - new Date(a.updatedAt).getTime()
    );
  }

  /**
   * Parse a session JSONL file and return user/assistant messages for display.
   *
   * Key design decisions:
   * 1. tool_result blocks live inside user messages (not assistant messages) in JSONL.
   *    We associate them to the preceding assistant's tool_use blocks via a shared
   *    object reference map — mutations propagate back into the messages array automatically.
   * 2. thinking blocks are extracted from assistant content and returned as a separate field.
   * 3. User messages that contain ONLY tool_result blocks (synthetic) are not shown in chat.
   */
  async getSessionMessages(
    sessionId: string,
    opts?: { offset?: number; limit?: number }
  ): Promise<{
    role: "user" | "assistant" | "system";
    content: string;
    thinking?: string;
    toolCalls?: {
      id: string;
      toolName: string;
      toolInput: Record<string, unknown>;
      result?: string;
      isError?: boolean;
      status: "done" | "error";
    }[];
    taskResult?: {
      costUsd?: number;
      durationMs?: number;
      numTurns?: number;
      inputTokens?: number;
      outputTokens?: number;
      cacheReadTokens?: number;
    };
    compactData?: {
      tokensBefore: number;
      tokensAfter: number;
      summary?: string;
    };
    rolledBack?: boolean;
    timestamp?: number;
    total?: number;  // only on the first page (offset=0 or undefined)
  }[]> {
    const projectsDir = path.join(getClaudeHome(), "projects");
    let filePath: string | null = null;

    try {
      const dirs = await fs.readdir(projectsDir);
      for (const dir of dirs) {
        const candidate = path.join(projectsDir, dir, `${sessionId}.jsonl`);
        const exists = await fs.access(candidate).then(() => true).catch(() => false);
        if (exists) { filePath = candidate; break; }
      }
    } catch { return []; }

    if (!filePath) return [];

    const raw = await fs.readFile(filePath, "utf-8").catch(() => "");
    const lines = raw.split("\n").filter((l) => l.trim());

    type ToolCallEntry = {
      id: string;
      toolName: string;
      toolInput: Record<string, unknown>;
      result?: string;
      isError?: boolean;
      status: "done" | "error";
    };

    const messages: ReturnType<SessionManager["getSessionMessages"]> extends Promise<infer T> ? T : never = [];
    // Shared-reference map: tool_use_id → ToolCallEntry object that is also
    // inside the messages array. Mutating via this map updates messages in-place.
    const toolCallsByUseId = new Map<string, ToolCallEntry>();

    // Parallel array: usage data per message index (for assistant entries)
    interface UsageData {
      input_tokens?: number;
      output_tokens?: number;
      cache_creation_input_tokens?: number;
      cache_read_input_tokens?: number;
    }
    const messageUsages: (UsageData | undefined)[] = [];

    // ── UUID chain tracking for rollback detection ──
    // Track every JSONL entry's uuid and parentUuid so we can determine the
    // "active" message chain (= walk backwards from the last entry).
    // Messages NOT on the active chain are on a dead/rolled-back branch.
    const uuidToParent = new Map<string, string | null>();
    // Map: JSONL entry uuid → index in our `messages` array (-1 if not mapped)
    const uuidToMsgIdx = new Map<string, number>();
    let lastEntryUuid: string | null = null;

    // Track compact_boundary UUIDs to capture the isCompactSummary user entry
    // that follows each compact_boundary (contains the summary text).
    const compactBoundaryUuids = new Set<string>();
    // Map: compact_boundary uuid → index in messages array (for patching summary/tokensAfter)
    const compactUuidToMsgIdx = new Map<string, number>();
    // Track: the next real assistant usage after each compact message index
    // (for computing tokensAfter)
    const compactMsgIdxNeedingAfter = new Set<number>();

    for (const line of lines) {
      try {
        const entry = JSON.parse(line) as Record<string, unknown>;
        const type = entry.type as string;

        // Track UUID chain for every entry (rollback detection)
        const entryUuid = entry.uuid as string | undefined;
        const entryParent = entry.parentUuid as string | undefined;
        if (entryUuid) {
          uuidToParent.set(entryUuid, entryParent ?? null);
          lastEntryUuid = entryUuid;
        }

        // ── isCompactSummary user entry: extract summary for the preceding compact_boundary ──
        if (type === "user" && entry.isCompactSummary === true) {
          const parentId = entryParent;
          if (parentId && compactBoundaryUuids.has(parentId)) {
            const compactIdx = compactUuidToMsgIdx.get(parentId);
            if (compactIdx !== undefined && messages[compactIdx]?.compactData) {
              // Extract summary from the compact continuation message content
              const rawContent = (entry.message as Record<string, unknown>)?.content;
              const summaryText = typeof rawContent === "string" ? rawContent : "";
              // Trim "This session is being continued..." preamble to get the analysis
              const analysisMatch = summaryText.match(/(?:Analysis:|Summary:)\s*([\s\S]*)/i);
              const full = analysisMatch
                ? analysisMatch[1].trim()
                : summaryText;
              const summary = full.length > 1000
                ? full.substring(0, 1000) + "…"
                : full;
              if (summary) {
                messages[compactIdx] = {
                  ...messages[compactIdx],
                  compactData: { ...messages[compactIdx].compactData!, summary },
                };
              }
            }
          }
          // Don't add isCompactSummary as a visible message — it's internal
          if (entryUuid) uuidToMsgIdx.set(entryUuid, -1);
          continue;
        }

        if (type === "assistant") {
          const msg = entry.message as { content?: unknown; usage?: UsageData } | undefined;
          if (!msg) continue;

          const blocks = Array.isArray(msg.content)
            ? (msg.content as Record<string, unknown>[])
            : [];

          let textContent = "";
          let thinkingContent = "";
          const toolCalls: ToolCallEntry[] = [];

          for (const block of blocks) {
            const btype = block.type as string;
            if (btype === "text") {
              textContent += (block.text as string) || "";
            } else if (btype === "thinking") {
              thinkingContent += (block.thinking as string) || "";
            } else if (btype === "tool_use" && block.id) {
              const tc: ToolCallEntry = {
                id: block.id as string,
                toolName: (block.name as string) || "unknown",
                toolInput: (block.input as Record<string, unknown>) || {},
                status: "done",  // will be updated when tool_result arrives
              };
              toolCalls.push(tc);
              toolCallsByUseId.set(block.id as string, tc);
            }
          }

          const ts = typeof entry.timestamp === "string"
            ? new Date(entry.timestamp).getTime()
            : undefined;

          // Filter out CLI placeholder responses (e.g. "/compact" → "No response requested.")
          const trimmedText = textContent.trim();
          const isPlaceholder = trimmedText === "No response requested.";
          const effectiveText = isPlaceholder ? "" : textContent;

          if (effectiveText || toolCalls.length > 0 || thinkingContent) {
            const msgIdx = messages.length;
            messages.push({
              role: "assistant",
              content: effectiveText,
              thinking: thinkingContent || undefined,
              toolCalls: toolCalls.length > 0 ? toolCalls : undefined,
              timestamp: ts,
            });
            // Record usage from this assistant entry (parallel array)
            messageUsages.push(msg.usage || undefined);
            if (entryUuid) uuidToMsgIdx.set(entryUuid, msgIdx);

            // If there are compact messages awaiting tokensAfter, compute from this usage
            if (compactMsgIdxNeedingAfter.size > 0 && msg.usage) {
              // Only use non-synthetic assistant messages (synthetic have 0 tokens)
              const totalInput = (msg.usage.input_tokens ?? 0)
                + (msg.usage.cache_creation_input_tokens ?? 0)
                + (msg.usage.cache_read_input_tokens ?? 0);
              if (totalInput > 0) {
                for (const cidx of compactMsgIdxNeedingAfter) {
                  if (messages[cidx]?.compactData) {
                    messages[cidx] = {
                      ...messages[cidx],
                      compactData: { ...messages[cidx].compactData!, tokensAfter: totalInput },
                    };
                  }
                }
                compactMsgIdxNeedingAfter.clear();
              }
            }
          }

        } else if (type === "user") {
          const msg = entry.message as { content?: unknown } | undefined;
          if (!msg) continue;

          const rawContent = msg.content;
          const ts = typeof entry.timestamp === "string"
            ? new Date(entry.timestamp).getTime()
            : undefined;

          if (Array.isArray(rawContent)) {
            let textContent = "";

            for (const block of rawContent as Record<string, unknown>[]) {
              const btype = block.type as string;
              if (btype === "tool_result") {
                // Associate result with the previously registered tool_use entry (by reference)
                const toolUseId = block.tool_use_id as string;
                const tc = toolCallsByUseId.get(toolUseId);
                if (tc) {
                  const content = block.content;
                  if (typeof content === "string") {
                    tc.result = content;
                  } else if (Array.isArray(content)) {
                    // 检查是否包含 image 块（MCP 截图等）
                    const hasImage = (content as { type: string }[]).some((b) => b.type === "image");
                    if (hasImage) {
                      // 保留完整 JSON（含 image base64），前端 extractImageSrc 可解析
                      tc.result = JSON.stringify(content);
                    } else {
                      // 纯文本结果，拼接 text 块
                      tc.result = (content as { type: string; text?: string }[])
                        .filter((b) => b.type === "text")
                        .map((b) => b.text || "")
                        .join("\n");
                    }
                  } else {
                    tc.result = JSON.stringify(content);
                  }
                  tc.isError = (block.is_error as boolean) || false;
                  tc.status = tc.isError ? "error" : "done";
                }
              } else if (btype === "text" && block.text) {
                textContent += block.text as string;
              }
            }

            // Only push as visible user message if there's real text content.
            // Filter out CLI-internal messages:
            //   "[...]" — system tags like [Request interrupted by user]
            //   "<...>" — XML-tagged local commands (local-command-caveat, command-name, etc.)
            //   "This session is being continued" — compact continuation summaries
            const text = textContent.trim();
            if (text && !isInternalMessage(text)) {
              if (entryUuid) uuidToMsgIdx.set(entryUuid, messages.length);
              messages.push({ role: "user", content: text, timestamp: ts });
              messageUsages.push(undefined);
            } else if (entryUuid) {
              uuidToMsgIdx.set(entryUuid, -1); // skipped internal message
            }

          } else if (typeof rawContent === "string") {
            const text = rawContent.trim();
            if (text && !isInternalMessage(text)) {
              if (entryUuid) uuidToMsgIdx.set(entryUuid, messages.length);
              messages.push({ role: "user", content: text, timestamp: ts });
              messageUsages.push(undefined);
            } else if (entryUuid) {
              uuidToMsgIdx.set(entryUuid, -1);
            }
          }
        }
        // ── type === "system" + subtype === "compact_boundary": create compact divider ──
        if (type === "system" && entry.subtype === "compact_boundary") {
          const meta = (entry.compactMetadata ?? entry.compact_metadata) as Record<string, unknown> | undefined;
          const preTokens = Number(meta?.preTokens ?? meta?.pre_tokens ?? 0);

          const ts = typeof entry.timestamp === "string"
            ? new Date(entry.timestamp as string).getTime()
            : undefined;

          const compactMsgIdx = messages.length;
          messages.push({
            role: "system",
            content: "",
            compactData: { tokensBefore: preTokens, tokensAfter: 0 },
            timestamp: ts,
          });
          messageUsages.push(undefined);

          // Register for summary extraction and tokensAfter computation
          if (entryUuid) {
            compactBoundaryUuids.add(entryUuid);
            compactUuidToMsgIdx.set(entryUuid, compactMsgIdx);
            uuidToMsgIdx.set(entryUuid, compactMsgIdx);
          }
          compactMsgIdxNeedingAfter.add(compactMsgIdx);
        }

        // ── type === "result": attach taskResult to the last assistant message ──
        if (type === "result") {
          const costUsd = entry.cost_usd as number | undefined;
          const durationMs = entry.duration_ms as number | undefined;
          const numTurns = entry.num_turns as number | undefined;
          const usage = entry.usage as { input_tokens?: number; output_tokens?: number; cache_read_input_tokens?: number } | undefined;

          const taskResult = {
            costUsd,
            durationMs,
            numTurns,
            inputTokens: usage?.input_tokens,
            outputTokens: usage?.output_tokens,
            cacheReadTokens: usage?.cache_read_input_tokens,
          };

          // Attach to the last assistant message
          for (let i = messages.length - 1; i >= 0; i--) {
            if (messages[i].role === "assistant") {
              messages[i] = { ...messages[i], taskResult };
              break;
            }
          }
        }
        // Track non-message entry UUIDs too (result, system, etc.)
        if (entryUuid && !uuidToMsgIdx.has(entryUuid)) {
          uuidToMsgIdx.set(entryUuid, -1);
        }
      } catch { /* malformed line — skip */ }
    }

    // ── Determine active message chain via parentUuid walk ──
    // Walk from the last JSONL entry backwards through parentUuid to find the
    // "active" chain. Messages NOT on this chain are on rolled-back branches.
    if (lastEntryUuid && uuidToParent.size > 0) {
      const activeUuids = new Set<string>();
      let cur: string | null = lastEntryUuid;
      while (cur) {
        activeUuids.add(cur);
        cur = uuidToParent.get(cur) ?? null;
      }
      // Also follow logicalParentUuid chains: compact_boundary has parentUuid=null
      // but logicalParentUuid pointing to the pre-compact chain.
      // Re-scan entries to capture logicalParentUuid links
      for (const line of lines) {
        try {
          const entry = JSON.parse(line) as Record<string, unknown>;
          const uuid = entry.uuid as string | undefined;
          const logicalParent = entry.logicalParentUuid as string | undefined;
          if (uuid && logicalParent && activeUuids.has(uuid)) {
            // This active entry has a logical parent — walk that chain too
            let lp: string | null = logicalParent;
            while (lp && !activeUuids.has(lp)) {
              activeUuids.add(lp);
              lp = uuidToParent.get(lp) ?? null;
            }
          }
        } catch { /* skip */ }
      }

      // Mark messages not on the active chain as rolledBack
      for (const [uuid, msgIdx] of uuidToMsgIdx) {
        if (msgIdx >= 0 && !activeUuids.has(uuid)) {
          messages[msgIdx] = { ...messages[msgIdx], rolledBack: true };
        }
      }
    }

    // ── Synthesise taskResult from assistant message.usage ──
    // JSONL files do NOT contain "type":"result" entries (those only appear in
    // stream-json stdout). So we create synthetic taskResults from each assistant
    // entry's message.usage to populate LiveMonitor summaries and context gauge.
    // A "turn boundary" = last assistant message before the next user message or end.
    for (let i = 0; i < messages.length; i++) {
      if (messages[i].role !== "assistant") continue;
      // Already has a real taskResult (from a rare "result" entry) — skip
      if (messages[i].taskResult) continue;

      const isLastInTurn =
        i === messages.length - 1 || messages[i + 1]?.role === "user";
      if (!isLastInTurn) continue;

      // Find the best (latest) usage within this turn's assistant messages
      let usage: UsageData | undefined;
      for (let j = i; j >= 0 && messages[j].role === "assistant"; j--) {
        if (messageUsages[j]) { usage = messageUsages[j]; break; }
      }
      if (!usage) continue;

      const totalInput =
        (usage.input_tokens ?? 0) +
        (usage.cache_creation_input_tokens ?? 0) +
        (usage.cache_read_input_tokens ?? 0);

      messages[i] = {
        ...messages[i],
        taskResult: {
          inputTokens: totalInput,
          outputTokens: usage.output_tokens ?? 0,
          cacheReadTokens: usage.cache_read_input_tokens ?? 0,
        },
      };
    }

    // Apply pagination: return the last `limit` messages starting at `offset` from the end
    const total = messages.length;
    const limit = opts?.limit ?? total;
    const offset = opts?.offset ?? 0;
    // offset=0 means "from the end", offset=50 means "skip the last 50 and go further back"
    const end = Math.max(0, total - offset);
    const start = Math.max(0, end - limit);
    const page = messages.slice(start, end);

    // Tag the first message of the first page with total count
    if (page.length > 0 && offset === 0) {
      page[0] = { ...page[0], total };
    }

    return page;
  }

  /**
   * Parse file-history-snapshot entries from a session JSONL.
   *
   * Correctly handles the CLI's backup metadata format:
   * - trackedFileBackups values are { backupFileName, version, backupTime }, not raw strings
   * - isSnapshotUpdate entries are merged into the base snapshot (same messageId)
   * - User message content is extracted via uuid ↔ messageId matching
   */
  async getSessionCheckpoints(sessionId: string): Promise<CheckpointsResult> {
    const filePath = await this.findSessionJsonl(sessionId);
    if (!filePath) return { checkpoints: [], projectCwd: null };

    const raw = await fs.readFile(filePath, "utf-8").catch(() => "");
    const lines = raw.split("\n").filter((l) => l.trim());

    // Pass 1: collect user messages and snapshots
    const userMessages = new Map<string, { content: string; timestamp: string }>();
    // Base snapshots keyed by messageId
    const baseSnapshots = new Map<string, {
      messageId: string;
      timestamp: string;
      trackedFileBackups: Record<string, FileBackupMeta>;
    }>();

    let projectCwd: string | null = null;

    for (const line of lines) {
      try {
        const entry = JSON.parse(line) as Record<string, unknown>;
        const type = entry.type as string;

        if (type === "user") {
          const uuid = entry.uuid as string | undefined;
          const userType = entry.userType as string | undefined;
          if (!uuid || userType !== "external") continue;

          // Extract cwd from user messages
          if (!projectCwd && entry.cwd) {
            projectCwd = entry.cwd as string;
          }

          const msg = entry.message as { content?: unknown } | undefined;
          if (!msg) continue;
          const text = extractUserText(msg.content).trim();
          if (!text || isInternalMessage(text)) continue;

          const ts = (entry.timestamp as string) || "";
          userMessages.set(uuid, { content: text, timestamp: ts });
        }

        if (type === "file-history-snapshot") {
          const messageId = entry.messageId as string;
          const snapshot = entry.snapshot as Record<string, unknown> | undefined;
          const isUpdate = (entry.isSnapshotUpdate as boolean) ?? false;

          if (!snapshot || !messageId) continue;

          const backups = (snapshot.trackedFileBackups as Record<string, FileBackupMeta>) ?? {};
          const timestamp = (snapshot.timestamp as string) || "";

          if (isUpdate) {
            // Merge update into existing base snapshot
            const base = baseSnapshots.get(messageId);
            if (base) {
              Object.assign(base.trackedFileBackups, backups);
            }
          } else {
            baseSnapshots.set(messageId, {
              messageId,
              timestamp,
              trackedFileBackups: { ...backups },
            });
          }
        }
      } catch { /* malformed — skip */ }
    }

    // Pass 2: build CheckpointData from merged base snapshots
    const checkpoints: CheckpointData[] = [];

    for (const [msgId, snap] of baseSnapshots) {
      const userMsg = userMessages.get(msgId);
      const rawContent = userMsg?.content ?? "";
      const userContent = rawContent.slice(0, 60) + (rawContent.length > 60 ? "…" : "");

      const changedFiles = Object.entries(snap.trackedFileBackups).map(
        ([filePath, meta]) => ({
          path: filePath,
          backupFileName: meta.backupFileName,
          isNewFile: meta.backupFileName === null,
        })
      );

      checkpoints.push({
        messageId: msgId,
        userContent,
        timestamp: userMsg?.timestamp || snap.timestamp,
        changedFiles,
        hasFileChanges: changedFiles.length > 0,
      });
    }

    // Sort by timestamp ascending
    checkpoints.sort(
      (a, b) => new Date(a.timestamp).getTime() - new Date(b.timestamp).getTime()
    );

    return { checkpoints, projectCwd };
  }

  /**
   * Rollback files to a specific checkpoint.
   *
   * Reads the actual backup file contents from ~/.claude/file-history/{sessionId}/
   * and writes them back to disk. For files with backupFileName: null (new files
   * created after the checkpoint), the file is deleted.
   */
  async rollbackToCheckpoint(
    sessionId: string,
    messageId: string
  ): Promise<RollbackResult> {
    // Reuse getSessionCheckpoints to get properly merged snapshots + cwd
    const { checkpoints, projectCwd } = await this.getSessionCheckpoints(sessionId);

    if (checkpoints.length === 0) {
      return { success: false, fileResults: [], error: "No checkpoints found for this session" };
    }

    const target = checkpoints.find((cp) => cp.messageId === messageId);
    if (!target) {
      return { success: false, fileResults: [], error: "Checkpoint not found for this messageId" };
    }

    if (!projectCwd) {
      return { success: false, fileResults: [], error: "Cannot determine project working directory" };
    }

    if (!target.hasFileChanges) {
      return { success: true, fileResults: [], error: "No file changes in this checkpoint" };
    }

    const fileHistoryDir = path.join(getClaudeHome(), "file-history", sessionId);
    const fileResults: FileRollbackResult[] = [];

    for (const file of target.changedFiles) {
      const absolutePath = path.resolve(projectCwd, file.path);

      // Security check: ensure path is within project directory
      if (!isSubPath(projectCwd, absolutePath)) {
        fileResults.push({ path: file.path, action: "failed", error: "Path outside project directory" });
        logger.error(`[rollback] Path traversal blocked: ${file.path}`);
        continue;
      }

      if (file.backupFileName === null) {
        // New file created after checkpoint — delete it
        try {
          await fs.unlink(absolutePath);
          fileResults.push({ path: file.path, action: "deleted" });
          logger.info(`[rollback] Deleted new file: ${file.path}`);
        } catch (err: unknown) {
          if ((err as NodeJS.ErrnoException).code === "ENOENT") {
            fileResults.push({ path: file.path, action: "skipped" });
            logger.info(`[rollback] Already deleted: ${file.path}`);
          } else {
            fileResults.push({ path: file.path, action: "failed", error: String(err) });
            logger.error(`[rollback] Failed to delete ${file.path}: ${String(err)}`);
          }
        }
      } else {
        // Existing file — read backup content and restore
        const backupPath = path.join(fileHistoryDir, file.backupFileName);
        try {
          const content = await fs.readFile(backupPath);
          await fs.mkdir(path.dirname(absolutePath), { recursive: true });
          await fs.writeFile(absolutePath, content);
          fileResults.push({ path: file.path, action: "restored" });
          logger.info(`[rollback] Restored: ${file.path}`);
        } catch (err: unknown) {
          if ((err as NodeJS.ErrnoException).code === "ENOENT") {
            fileResults.push({ path: file.path, action: "failed", error: "Backup file not found (may have been cleaned up)" });
            logger.error(`[rollback] Backup not found: ${backupPath}`);
          } else {
            fileResults.push({ path: file.path, action: "failed", error: String(err) });
            logger.error(`[rollback] Failed to restore ${file.path}: ${String(err)}`);
          }
        }
      }
    }

    const hasFailures = fileResults.some((r) => r.action === "failed");
    return { success: !hasFailures, fileResults };
  }

  /**
   * Rename a session by updating its summary in sessions-index.json.
   * Falls back to creating the entry if it doesn't exist.
   */
  async renameSession(sessionId: string, name: string): Promise<boolean> {
    const projectsDir = path.join(getClaudeHome(), "projects");
    try {
      const dirs = await fs.readdir(projectsDir);
      for (const dir of dirs) {
        const jsonlPath = path.join(projectsDir, dir, `${sessionId}.jsonl`);
        const exists = await fs.access(jsonlPath).then(() => true).catch(() => false);
        if (!exists) continue;

        const indexPath = path.join(projectsDir, dir, "sessions-index.json");
        let indexData: { sessions?: Record<string, Record<string, unknown>> } = {};
        try {
          const raw = await fs.readFile(indexPath, "utf-8");
          indexData = JSON.parse(raw);
        } catch {
          // File doesn't exist or is malformed — create new
        }

        if (!indexData.sessions) indexData.sessions = {};
        if (!indexData.sessions[sessionId]) {
          indexData.sessions[sessionId] = { sessionId };
        }
        indexData.sessions[sessionId].summary = name;

        await fs.writeFile(indexPath, JSON.stringify(indexData, null, 2), "utf-8");
        logger.info(`Session renamed: ${sessionId} → "${name}"`);
        return true;
      }
    } catch {
      // ignore
    }
    return false;
  }

  async deleteSession(sessionId: string): Promise<boolean> {
    const projectsDir = path.join(getClaudeHome(), "projects");
    try {
      const dirs = await fs.readdir(projectsDir);
      for (const dir of dirs) {
        const filePath = path.join(projectsDir, dir, `${sessionId}.jsonl`);
        try {
          await fs.unlink(filePath);
          logger.info(`Session deleted: ${sessionId}`);
          return true;
        } catch {
          // Not in this directory, continue
        }
      }
    } catch {
      // Projects directory doesn't exist
    }
    return false;
  }
}
